# Generated by Django 3.1.1 on 2020-09-13 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dzial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(max_length=20, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupaRobocza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_grupy', models.CharField(max_length=40, unique=True)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_klienta', models.CharField(max_length=40, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RodzajeBledu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blad', models.CharField(max_length=100, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wiazka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_wiazki', models.CharField(max_length=40, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
                ('nazwa_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_pracownika', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=40)),
                ('zatrudniony', models.BooleanField(default=True)),
                ('dzial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.dzial')),
            ],
        ),
        migrations.CreateModel(
            name='Bledy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zlecenia', models.DecimalField(decimal_places=0, max_digits=8)),
                ('nr_kontrolera', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ilosc_skontrolowanych', models.DecimalField(decimal_places=0, max_digits=8)),
                ('ilosc_bledow', models.DecimalField(decimal_places=0, max_digits=5)),
                ('rodzaj_reklamacji', models.CharField(choices=[('wew', 'Reklamacja wewnętrzna'), ('zew', 'Reklamacja zewnętrzna')], default='wew', max_length=5)),
                ('komputer_user', models.CharField(default='mirek', max_length=10)),
                ('komputer', models.CharField(default='Mirek-PC', max_length=30)),
                ('data_dodania', models.DateTimeField(default=datetime.datetime(2020, 9, 13, 10, 3, 10, 929383), verbose_name='data dodania')),
                ('skasowany', models.BooleanField(default=False)),
                ('autor_wpisu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.autor')),
                ('blad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.rodzajebledu')),
                ('nr_budujacego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.pracownik')),
                ('nr_grupy_roboczej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.gruparobocza')),
                ('nr_wiazki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.wiazka')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='dzial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.dzial'),
        ),
        migrations.AddField(
            model_name='autor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
