# Generated by Django 3.1.1 on 2020-09-23 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bledy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodzajReklamacji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=20, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bledy',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 22, 9, 14, 959208), verbose_name='data dodania'),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='rodzaj_reklamacji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.rodzajreklamacji'),
        ),
    ]
