# Generated by Django 3.1.1 on 2020-09-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bledy', '0002_auto_20200923_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bledy',
            name='blad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bledy.rodzajebledu'),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='data_dodania',
            field=models.DateField(default='2020-09-30', verbose_name='data dodania'),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='ilosc_bledow',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='ilosc_skontrolowanych',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='nr_budujacego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bledy.pracownik'),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='nr_grupy_roboczej',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bledy.gruparobocza'),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='nr_kontrolera',
            field=models.DecimalField(decimal_places=0, default=999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='nr_wiazki',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bledy.wiazka'),
        ),
        migrations.AlterField(
            model_name='bledy',
            name='rodzaj_reklamacji',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bledy.rodzajreklamacji'),
        ),
    ]
